Config = {}

Config.UseESX = true
Config.PoliceAlertCooldown = 30

RegisterNetEvent('angelicxs-MDetector:CustomDisptach')
AddEventHandler('angelicxs-MDetector:CustomDisptach', function(coordz)

end)

Config.Detectors = {

	MRPD = {
		{	
			coords = {466.38, -994.68, 30.46}, detectRadius = 0.8, soundRadious = 10, timer = 2000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			jobsExempt = {
				["police"] = 0,
				["ambulance"] = 0,
			},
			UseMainList = true,
		},
		{
			coords = {466.71, -992.46, 30.46}, detectRadius = 1.8, soundRadious = 10, timer = 2000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			jobsExempt = {
				["police"] = 0,
				["ambulance"] = 0,
			},
			UseMainList = true,
		},
		{
			coords = {478.62, -986.51, 29.96}, detectRadius = 1.8, soundRadious = 10, timer = 2000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			jobsExempt = {
				["police"] = 0,
				["ambulance"] = 0,
			},
			UseMainList = true,
		},
		{
			coords = {479.88, -986.61, 29.96}, detectRadius = 1.8, soundRadious = 10, timer = 2000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			jobsExempt = {
				["police"] = 0,
				["ambulance"] = 0,
			},
			UseMainList = true,
		},
		{
			coords = {475.94, -991.36, 25.47}, detectRadius = 1.8, soundRadious = 10, timer = 2000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			jobsExempt = {
				["police"] = 0,
				["ambulance"] = 0,
			},
			UseMainList = true,
		},
	},


 	Vanilla = {
		{
			coords = {129.0024, -1298.9150, 29.2327}, detectRadius = 1, soundRadious = 10, timer = 5000, sound = 'VEHICLES_HORNS_AMBULANCE_WARNING',
			items = {
				"fireplace",
			},
	
		},
	},

}

Config.MetalItems = {
	'weapon_dagger',
	'weapon_crowbar',
	'weapon_flashlight',
	'weapon_golfclub',
	'weapon_hammer',
	'weapon_hatchet',
	'weapon_knuckle',
	'weapon_knife',
	'weapon_machete',
	'weapon_switchblade',
	'weapon_wrench',
	'weapon_battleaxe',
	'weapon_handcuffs',
	'weapon_pistol',
	'weapon_pistol_mk2',
	'weapon_combatpistol',
	'weapon_appistol',
	'weapon_stungun',
	'weapon_pistol50',
	'weapon_snspistol',
	'weapon_heavypistol',
	'weapon_vintagepistol',
	'weapon_flaregun',
	'weapon_marksmanpistol',
	'weapon_revolver',
	'weapon_revolver_mk2',
	'weapon_doubleaction',
	'weapon_snspistol_mk2',
	'weapon_raypistol',
	'weapon_navyrevolver',
	'weapon_gadgetpistol',
	'weapon_microsmg',
	'weapon_smg',
	'weapon_smg_mk2',
	'weapon_assaultsmg',
	'weapon_combatpdw',
	'weapon_machinepistol',
	'weapon_minismg',
	'weapon_raycarbine',
	'weapon_pumpshotgun',
	'weapon_sawnoffshotgun',
	'weapon_assaultshotgun',
	'weapon_bullpupshotgun',
	'weapon_musket',
	'weapon_heavyshotgun',
	'weapon_dbshotgun',
	'weapon_autoshotgun',
	'weapon_combatshotgun',
	'weapon_pumpshotgun_mk2',
	'weapon_assaultrifle',
	'weapon_assaultrifle_mk2',
	'weapon_carbinerifle',
	'weapon_carbinerifle_mk2',
	'weapon_advancedrifle',
	'weapon_specialcarbine',
	'weapon_bullpuprifle',
	'weapon_compactrifle',
	'weapon_specialcarbine_mk2',
	'weapon_bullpuprifle_mk2',
	'weapon_militaryrifle',
	'weapon_mg',
	'weapon_combatmg',
	'weapon_gusenberg',
	'weapon_combatmg_mk2',
	'weapon_sniperrifle',
	'weapon_heavysniper',
	'weapon_marksmanrifle',
	'weapon_remotesniper',
	'weapon_heavysniper_mk2',
	'weapon_marksmanrifle_mk2',
	'weapon_rpg',
	'weapon_grenadelauncher_smoke',
	'weapon_grenadelauncher',
	'weapon_minigun',
	'weapon_firework',
	'weapon_railgun',
	'weapon_hominglauncher',
	'weapon_compactlauncher',
	'weapon_rayminigun',
	'weapon_grenade',
	'weapon_bzgas',
	'weapon_proxmine',
	'weapon_pipebomb',
	'weapon_smokegrenade',
	'weapon_flare',
	'weapon_fireextinguisher',
	'pistol_flashlight',
	'pistol_suppressor',
	'microsmg_scope',
	'smg_drum',
	'smg_scope',
	'machinepistol_drum',
	'combatpdw_drum',
	'combatpdw_scope',
	'shotgun_suppressor',
	'heavyshotgun_drum',
	'assaultrifle_drum',
	'rifle_flashlight',
	'rifle_suppressor',
	'carbinerifle_drum',
	'carbinerifle_scope',
	'specialcarbine_drum',
	'compactrifle_drum',
	'sniperrifle_defaultclip',
	'sniper_scope',
	'snipermax_scope',
	'marksmanrifle_scope',
	'pistol_ammo',
	'rifle_ammo',
	'smg_ammo',
	'shotgun_ammo',
	'mg_ammo',
	'snp_ammo',
	'emp_ammo',
	'metalscrap',
	'copper',
	'aluminum',
	'aluminumoxide',
	'iron',
	'ironoxide',
	'steel',
	'lockpick',
	'advancedlockpick',
	'electronickit',
	'gatecrack',
	'screwdriverset',
	'drill',
	'nitrous',
	'repairkit',
	'advancedrepairkit',
	'tunerlaptop',
	'harness',
	'phone',
	'radio',
	'iphone',
	'samsungphone',
	'laptop',
	'tablet',
	'fitbit',
	'radioscanner',
	'pinger',
	'trojan_usb',
	'cryptostick',
	'rolex',
	'diamond_ring',
	'goldchain',
	'10kgoldchain',
	'goldbar',
	'handcuffs',
	'police_stormram',
	'diving_gear',
	'binoculars',
	'lighter',
	'labkey',
}
